### ISSUE TITLE
Statistics pheonotype

### ISSUE THREAD

**Issue by ahasuni** [JacobIMarsh/crosshap#2]
Hi there,

Are there any statistical tests recommended here for phenotypes?

Hasan

**Comment by jacobimarsh** [comment]
Hi Hasan!

None in particular, though in the past I've done two sample t-tests, comparing the phenotype scores of individuals with a haplotype of interest with the phenotype scores across all other haplotypes. 
See Table S8 from https://doi.org/10.1007/s00122-022-04045-8

I'm sure other tests may be appropriate!

Also, for help accessing specific results of the haplotyping, see the final section in the Getting started vignette.

Jacob
